blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/[PROJECT_OWNER_FILL_IN_ORG_NAME]/[PROJECT_OWNER_FILL_IN_REPO_NAME]/discussions/new
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
