name: ci
on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'webpack/**'
      - 'yarn.lock'
      - 'package.json'
      - 'tsconfig.json'
      - '.github/workflows/on_pull_request.yml'
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
      - name: yarn install
        run: |
          yarn install
  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
      - name: yarn lint
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
      - name: yarn test
        run: yarn test
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
      - name: build
        run: yarn build
      - name: Update manifest.json
        run: |
          npx dot-json@1 dist/manifest.json version dummy
      - name: Archive
        run: |
          zip -r extension.zip ./dist
      - name: Check Archive
        run: |
          rm -rf ./dist
          unzip extension.zip
          ls -lR ./dist
