name: schedule create release pull request

on:
  schedule:
    - cron: 0 6 * * 5
  push:
    branches:
      - develop

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create Branch
        run: git checkout -b release/gha_${{ github.run_id }}

      - name: Push Branch
        run: git push origin release/gha_${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        id: new-pr
        with:
          commit-message: release
          base: main
          delete-branch: true
          title: '[${{ github.run_id }}]auto release'
          body: '[${{ github.run_id }}]auto release'
          branch: 'release/gha_${{ github.run_id }}'
